hmcts/azure-devops-agent

- Dockerfile
Add openjdk-8 and azcopy
```
[ ] Yes
[x] No
```
> add java and azcopy

- Dockerfile
> trigger build

- Dockerfile
> ditch azcopy

- Dockerfile
- start.sh
[AB#328]
```
[ ] Yes
[x] No
```
> Use standard ubuntu base image

- Dockerfile
Install `make` utility
```
[ ] Yes
[x] No
```
> Install make

- Dockerfile
- start.sh
https://tools.hmcts.net/jira/browse/DTSPO-231
- added support to set AZP_TOKEN environment variable from file mount read from key vault
- removed docker image (docker in docker not required)
```
[ ] Yes
[x] No
```
> added token read from file and removed docker

- start.sh
https://tools.hmcts.net/jira/browse/DTSPO-231
Fixed AZP_TOKEN env variable path.
```
[ ] Yes
[x] No
```
> fixed AZP_TOKEN env variable path

- start.sh
https://tools.hmcts.net/jira/browse/DTSPO-231
Removed exit statement - not required here
Update check - for file
```
[ ] Yes
[x] No
```
> fixed missing condition and action

- Dockerfile
https://tools.hmcts.net/jira/browse/DTSPO-231
Updated JDK version to 11
v11 required by MI Data Platform
Image build tested locally
```
[ ] Yes
[x] No
```
> Updated JDK to v11

- start.sh
Updated mount path to use a descriptive name (and match the updated key vault secret)
```
[ ] Yes
[x] No
```
> Update PAT mount path

- Dockerfile
https://tools.hmcts.net/jira/browse/DTSPO-3734
Adding Python3 venv.
```
[ ] Yes
[X] No
```
> Adding Python3 venv.

- acr-build-task.sh
fix image tag to be flux v2 compliant
```
[ ] Yes
[x] No
```
> DTSPO-5577 - fix image tag to be flux v2 compliant

- Dockerfile
https://tools.hmcts.net/jira/browse/DTSPO-8260
- Add Ansible PPA source
- Add Ansible via apt
```
[ ] Yes
[x] No
```
> DTSPO-8260: Add Ansible to Agent

- Dockerfile
https://tools.hmcts.net/jira/browse/DTSPO-8260
Update Ansible install to be further in the dockerfile as require `software-properties-common` to be available
```
[ ] Yes
[x] No
```
> DTSPO-8260: Agent Ansible

- Dockerfile
**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```
> Version bump

- Dockerfile
Add python packages
```
[ ] Yes
[x] No
```
> Add python packages

- Dockerfile
Adds python3-packaging package to the vsts agent image.
Fixes: https://github.com/hmcts/cnp-azuredevops-libraries/pull/141 
```
[ ] Yes
[x] No
```
> Add python3-packaging to dockerfile

- Dockerfile
N/A
Install bsdmainutils package (for column command) and [YQ](https://github.com/mikefarah/yq/tree/master)
```
[ ] Yes
[x] No
```
> feat: added bsdmainutils & yq

- start.sh
Replacing pat token with managed identity
> DTSPO-13833 Replace pat token with managed identity

- Dockerfile
N/A
Add powershell due to issues encountered by MI.
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> fix: add powershell
